"""Evidence-State I/O public API."""

from .canonical import (
    CANONICALIZATION_PROFILE,
    DIGEST_ALGORITHM,
    canonical_digest,
    canonical_json_bytes,
    verify_canonical_digest,
)
from .coverage import (
    CoverageAssessment,
    CoverageComponent,
    CoverageIssue,
    CoveragePolicy,
    evaluate_coverage,
)
from .emptybench import (
    EmptyBenchCase,
    EmptyBenchOutcome,
    EmptyBenchReport,
    demo_cases,
    parse_cases,
    run_emptybench,
    run_seed_emptybench,
    seed_cases,
)
from .gate import (
    GateDecision,
    GateReason,
    NegativeClaimPolicy,
    NegativeClaimRequest,
    evaluate_negative_claim,
)
from .models import (
    ClaimMode,
    CoverageEvidence,
    EvidenceEnvelope,
    EvidenceState,
    MAX_SOURCE_ACCOUNTING_ENTRIES,
    ModelValidationError,
    PopulationBasis,
    QueryScope,
    SourceDescriptor,
    SourceObservation,
    SourceObservationStatus,
    SourceRequirement,
    SourceRole,
    bounded_ascii_identifier,
)
from .sources import (
    SourceAccountingAssessment,
    SourceIssue,
    SourceIssueCode,
    evaluate_source_accounting,
)

__all__ = [
    "CANONICALIZATION_PROFILE",
    "DIGEST_ALGORITHM",
    "ClaimMode",
    "CoverageAssessment",
    "CoverageComponent",
    "CoverageEvidence",
    "CoverageIssue",
    "CoveragePolicy",
    "EmptyBenchCase",
    "EmptyBenchOutcome",
    "EmptyBenchReport",
    "EvidenceEnvelope",
    "EvidenceState",
    "GateDecision",
    "GateReason",
    "MAX_SOURCE_ACCOUNTING_ENTRIES",
    "ModelValidationError",
    "NegativeClaimPolicy",
    "NegativeClaimRequest",
    "PopulationBasis",
    "QueryScope",
    "SourceAccountingAssessment",
    "SourceDescriptor",
    "SourceIssue",
    "SourceIssueCode",
    "SourceObservation",
    "SourceObservationStatus",
    "SourceRequirement",
    "SourceRole",
    "bounded_ascii_identifier",
    "canonical_digest",
    "canonical_json_bytes",
    "demo_cases",
    "evaluate_coverage",
    "evaluate_negative_claim",
    "evaluate_source_accounting",
    "parse_cases",
    "run_emptybench",
    "run_seed_emptybench",
    "seed_cases",
    "verify_canonical_digest",
]

__version__ = "0.2.0"
